import { Jost } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
<link
  href='https://api.fontshare.com/v2/css?f[]=chillax@400&f[]=panchang@700&display=swap'
  rel='stylesheet'
></link>;

const font1 = Jost({
  subsets: ["latin"],
  weight: ["400","500", "600", "900"],
  display: "swap",
  variable: "--sand",
});

export const metadata = {
  title: "CodeVista",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`bg-background container mx-auto min-h-screen xl:px-28 lg:px-10 px-5 font ${font1.variable} pattern`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
